import { useState } from 'react'

const destinations = [
  ['Karnataka', 'Mysuru', 'Palace cities, coffee hills, and ancient ruins', '12.3052° N'],
  ['Rajasthan', 'Udaipur', 'Lakes, forts, and stories in sandstone', '24.5764° N'],
  ['Kerala', 'Munnar', 'Tea trails and slow days in the Western Ghats', '10.0889° N'],
]

export default function Home({ onPlan, onExplore, onDemo, onLive, onSafety, onAI }) {
  const [activeDestination, setActiveDestination] = useState(0)
  return <main className="home-page">
    <header className="site-nav"><button className="site-brand" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}><span>✦</span><strong>BharatTrails <i>AI</i></strong></button><nav><button onClick={onPlan}>Plan Trip</button><button onClick={onExplore}>Explore India</button><button onClick={onLive}>Live Mode</button><button onClick={onSafety}>Safety</button><button onClick={onAI}>Bharat AI</button><a href="#why">Why BharatTrails</a></nav><button className="nav-demo" onClick={onDemo}>Launch Judge Demo <span>→</span></button></header>
    <section className="home-hero"><div className="hero-grid-art"><span className="hero-orbit orbit-one" /><span className="hero-orbit orbit-two" /><span className="hero-sun" /><span className="hero-land land-one" /><span className="hero-land land-two" /><div className="hero-coordinate">20° 35′ N<br /><b>INDIA / IN</b></div><div className="hero-art-label">ONE COUNTRY<br /><em>MANY WORLDS</em></div></div><div className="home-hero-copy"><p className="home-eyebrow">INTELLIGENT TRAVEL, ROOTED HERE</p><h1>Explore India.<br /><em>Your journey,</em><br />intelligently planned.</h1><p>AI-powered travel planning that adapts to your budget, interests, weather, traffic, and real-world conditions.</p><div className="home-actions"><button className="primary-action" onClick={onPlan}>Plan My India Trip <span>↗</span></button><button className="text-action" onClick={onExplore}>Explore India <span>→</span></button></div><div className="hero-proof"><span><b>50+</b> curated places</span><span><b>100%</b> India-focused</span><span><b>24/7</b> ready to adapt</span></div></div></section>
    <section className="signal-strip"><span>✦ BUILT FOR THE JOURNEY AHEAD</span><div><b>Preferences</b><i>→</i><b>Live conditions</b><i>→</i><b>AI decisions</b><i>→</i><b>Your best route</b></div></section>
    <section className="destination-section" id="explore"><div className="section-heading"><div><p className="home-eyebrow">A COUNTRY OF DETOURS</p><h2>Start somewhere<br /><em>meaningful.</em></h2></div><button className="text-action" onClick={onExplore}>View all destinations →</button></div><div className="destination-feature"><div className="destination-visual"><div className="visual-number">0{activeDestination + 1}</div><div className="visual-location">{destinations[activeDestination][3]}<br /><span>CURATED ROUTE</span></div><div className={`destination-scene scene-${activeDestination}`}><span className="scene-sun" /><span className="scene-arch" /><span className="scene-mountain" /></div></div><div className="destination-list">{destinations.map(([region, name, copy], index) => <button className={activeDestination === index ? 'destination-row active' : 'destination-row'} key={name} onClick={() => setActiveDestination(index)}><span className="destination-index">0{index + 1}</span><span><small>{region}</small><strong>{name}</strong><em>{copy}</em></span><b>↗</b></button>)}</div></div></section>
    <section className="why-section" id="why"><div className="why-statement"><p className="home-eyebrow">MORE THAN A MAP</p><h2>Travel plans should<br /><em>move with you.</em></h2><p>Most travel apps give you information. BharatTrails makes the next decision with you, balancing what you want with what the day brings.</p></div><div className="feature-rail"><article><span>01</span><b>Personal by design</b><p>Your pace, budget, food, and curiosity set the route.</p></article><article><span>02</span><b>Always responsive</b><p>Rain, traffic, crowds, or a change of heart never end the day.</p></article><article><span>03</span><b>Rooted in India</b><p>Local places, practical context, and Indian travel realities.</p></article></div></section>
    <footer className="home-footer"><span>BHARATTRAILS AI</span><span>Intelligent journeys, deeply Indian.</span><span>© 2026</span></footer>
  </main>
}
